// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXD6RweoQlmr1UTg1SAhRP8zWO-0lBH3k',
    appId: '1:719204243926:web:282b0281d1d7583ecfec77',
    messagingSenderId: '719204243926',
    projectId: 'natzard-99190',
    authDomain: 'natzard-99190.firebaseapp.com',
    storageBucket: 'natzard-99190.appspot.com',
    measurementId: 'G-QVWTL0G7CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YVxLXWkFQkQwakwjYctnideSDTFmjXg',
    appId: '1:719204243926:android:59e307079a80da1acfec77',
    messagingSenderId: '719204243926',
    projectId: 'natzard-99190',
    storageBucket: 'natzard-99190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUMg9Zo_y_CcyM3RmTWBLKxK46Q0C24A',
    appId: '1:719204243926:ios:e1ffdb15fdc9261acfec77',
    messagingSenderId: '719204243926',
    projectId: 'natzard-99190',
    storageBucket: 'natzard-99190.appspot.com',
    iosClientId: '719204243926-tg6582vl8ct9ebe6t0n6nqllob4526s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.natzard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUMg9Zo_y_CcyM3RmTWBLKxK46Q0C24A',
    appId: '1:719204243926:ios:e1ffdb15fdc9261acfec77',
    messagingSenderId: '719204243926',
    projectId: 'natzard-99190',
    storageBucket: 'natzard-99190.appspot.com',
    iosClientId: '719204243926-tg6582vl8ct9ebe6t0n6nqllob4526s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.natzard',
  );
}
